# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47a60b7b49120351d320a8d515cd0d1f074c84aa4007757e8d8362b7779faa100abf16c7b483c8bb00911cb164c04682755e4cc0817164abf60924b2991d5037

test:
  secret_key_base: 1f9651a489456aa9c1ead96a4f673cb617b1453de1cfaf25aa6ba6746a81189f1c9181523a2f0895b2db8d6a6f94c16ade0c496355df7872015053c39bf8d2d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
